### ISSUE TITLE
weblogic 12.1.2 donot work with Spring xml configuration

### ISSUE THREAD

**Issue by xsunil** [jsr107/RI#47]
My spring application packed as war runs wihout problem on weblogic 12.1.3 so I tried to deploy same war into weblogic 12.2.1 where it causes java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/DispatcherServlet-servlet.xml]. It seems like DispatcherServlet servlet is initialized with XmlWebApplicationContext (default one) instead of AnnotationConfigEmbeddedWebApplicationContext in 12.2.1 even when war is the same. Has someone any idea what was changed in weblogic implementation since previous version what is causing this problem? 

Using same war: 

in WLS 12.1.3 it is working without issue, application configures using annotations/java 
in WLS 12.2.1 the same application looks for xml configuration at some point instead of configuring it using annotations/java as in 12.1.3.

**Comment by cruftex** [comment]
@xsunil: This issue tracker scope is the reference implementation of the Java Caching standard (JSR107). I do not see how you issue relates to that.

Pls. close this issue and direct it to the appropriate channel. Thank!

**Comment by gregrluck** [comment]
Agree with Jens.
