### ISSUE TITLE
Concurrency issue on cache creation.

### ISSUE THREAD

**Issue by luisalves00** [jsr107/RI#66]
I'm having some concurrency issue when the cache is created. Here is the stack:

```
(default task-2) Unhandled exception.: javax.cache.CacheException: A Cache named [my-cache] already exists
	at org.ehcache.jsr107.Eh107CacheManager.createCache(Eh107CacheManager.java:198)
	at org.jsr107.ri.annotations.DefaultCacheResolverFactory.getCacheResolver(DefaultCacheResolverFactory.java:73)
	at com.la.cache.CacheResolverFactory.getCacheResolver(CacheResolverFactory.java:46)
	at com.la.cache.CacheResolverFactory$Proxy$_$$_WeldClientProxy.getCacheResolver(Unknown Source)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.createCacheResultMethodDetails(AbstractCacheLookupUtil.java:281)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.getMethodDetails(AbstractCacheLookupUtil.java:190)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.getCacheKeyInvocationContext(AbstractCacheLookupUtil.java:72)
	at org.jsr107.ri.annotations.AbstractCacheResultInterceptor.cacheResult(AbstractCacheResultInterceptor.java:49)
	at org.jsr107.ri.annotations.cdi.CacheResultInterceptor.cacheResult(CacheResultInterceptor.java:50)
```

looking at the code I see you have a  synchronized (cachesLock) { but no check if the cache is already created by other cache.

my code is something like this (I'm using DS repositories):

```
    @CacheResult(cacheName = "my-cache")
    public Location findLocationById(Integer id)
    {
        return findBy(id);  //<--- multiple threads get here at the same time...would be nice that just one created and populated the cache....so just one call to the database...but we want to minimize contention here.
    }
```

I'm not sure if it's a bug or if I'm doing something wrong...

**Comment by cruftex** [comment]
Hi Luis,

we (the maintainers) know that there are probably a lot concurrency issues in the RI. There is no real plan to fix them because the RI is not intended for production use. It serves as a reference in the standardization process. Some other standards use a production implementation as reference, JCache does not.

I am not sure what you are doing and why you use the RI in your project. Can you explain this? Isn't there an alternative annotations implementation around?

**Comment by luisalves00** [comment]
Hi Jens,

I want to use @CacheResult (and the other annotations) like @Cacheable in
Spring. Currently we are using EhCache as the provider and I found the RI
project. I don't know any other implementation...but I can look for one, or
try to do some synchronization logic on my side.

**Comment by cruftex** [comment]
Hi Luis,

I am pretty sure that spring comes with its own implementation of the JCache annotations.
You do not need to include the RI. Please double check with the Spring documentation.

**Comment by luisalves00** [comment]
I'm using CDI not Spring...that's why I came across you implementation.

**Comment by cruftex** [comment]
Ahh! I know Payara comes with good JCache CDI support, I don't know whether its the RI or some thing different. See:
https://payara.gitbooks.io/payara-server/content/v/154/documentation/extended-documentation/jcache.html

Maybe @smillidge can give a hint what CDI implementation should be used for JCache or whether it is actually the RI?

**Comment by luisalves00** [comment]
I'm currently using WildFly 10 + Deltaspike...and I only found https://github.com/tomitribe/jcache-cdi which seems to be a wrapper around your implementation.

**Comment by cruftex** [comment]
Okay, I am a little lost as well know. Hopefully somebody else can give some more details here.

**Comment by smillidge** [comment]
Payara does not use the RI for implementation of the CDI integration we have our own interceptors https://github.com/payara/Payara/tree/master/appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107. JCache functionality itself is provided by our embedded Hazelcast implementation.

**Comment by luisalves00** [comment]
Thanks Steve. I'm currently fixed the cache concurrency issue on my side. I'm also thinking on implementing the interceptors myself, as a concurrent cache miss does multiple calls to the database. But not sure what is the most efficient way to do this without much contention.

**Comment by cruftex** [comment]
@luisalves00 : also off-topic to here. The (hopefully) upcoming Spring implementation of cache2k uses `Cache.computeIfAbsent`, the JCache support in Sprint uses the entry processor, which give you blocking by default on some caches (e.g. cache2k....). For EHCache you need may need some additional setup, and I am not sure what the 3.0 and JCache support is doing. Further information:

- https://stackoverflow.com/questions/41374834/cache2k-read-through-and-blocking
- http://www.ehcache.org/documentation/2.7/apis/constructs.html

Anyhow, the problem you describe should be solved by the cache.
